# This workflow will build the code in the develop brach using Yarn.

name: Build develop branch

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm run build:vosviewer
    - run: npm run build:dimensions
    - run: npm run build:zeta-alpha
    - run: npm run build:rori

    - name: Upload VOSviewer Online build artifact
      uses: actions/upload-artifact@v2
      with:
        name: vosviewer-online-build
        path: dist/vosviewer-online
    - name: Upload Dimensions build artifact
      uses: actions/upload-artifact@v2
      with:
        name: vosviewer-online-dimensions-build
        path: dist/vosviewer-online-dimensions
    - name: Upload Zeta Alpha build artifact
      uses: actions/upload-artifact@v2
      with:
        name: vosviewer-online-zeta-alpa-build
        path: dist/vosviewer-online-zetaalpha
    - name: Upload RoRI build artifact
      uses: actions/upload-artifact@v2
      with:
        name: vosviewer-online-rori-build
        path: dist/vosviewer-online-rori
